repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: detect-private-key
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.5.0
    hooks:
    -   id: gitleaks
        args: ["--additional-config", ".gitleaks.toml", "--verbose"]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
