name: "CI"

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Secret Dection
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: .gitleaks.toml
