name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    name: Greetings
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            🎉 Were glad youve reported a issue. I hope that your contribution can elevate our community.
          pr-message: |
            🎉 Were glad youve make a pull-request. I hope that your contribution can elevate our community
